### ISSUE TITLE
Revise aut `config` result object to remove non-protocol properties

### ISSUE THREAD

**Issue by cmjc** [autonity/autonity#1040]
### Description

The `config` result object returns the contract addresses for the Autonity protocol contract configuration.

It contains the following field which is not in the protocol and should be removed from the `config` result:

- `nonStakableVestingContract`

### Related issues

- #1034 

### Implementation

https://github.com/autonity/autonity/blob/2f2ff5cf5a42b53ecbc0be277db639bffc969d0d/autonity/solidity/contracts/Autonity.sol#L128-L137

**Comment by lorenzo-dev1** [comment]
Closing as done, `nonStakableVestingContract` is not part of the protocol contracts anymore.
