### ISSUE TITLE
Refine the docker e2e test to co-exist with omission jailing protocols

### ISSUE THREAD

**Issue by Jason-Zhangxin-Chen** [autonity/autonity#1043]
The current testcases in the Docker e2e test playbook cannot co-exist with the new omission jailing protocols. Therefore, we need to rewrite these test contexts to be compatible with the new omission jailing protocol.

The proposed solution is:
- Create an independent blockchain life-cycle for each test case.
- Divide the playbook into multiple ones, each with its own individual CI job to speed up the testing process.

**Comment by lorenzo-dev1** [comment]
Closing as done
