### ISSUE TITLE
Test linearizability, liveness and security properties

### ISSUE THREAD

**Issue by JekaMas** [autonity/autonity#265]
As a developer of distributed system a need tools to test not only the code but properties of the distributed system.
So we need to have
* unit tests to check and document actual implementation
* e2e tests to check API and basic network cases
* fuzzing testing as a part of security
* memory leaks tests
* linearizability checking, liveness and security properties tests

This issue is about the last point of the lint.

Before spending years on own test framework we need to check if there is a tool suitable for us to test Autonity and integrate this testing into CI.

This tool should be open source, free and quite powerful.

As a first candidate, we could try https://github.com/jepsen-io/jepsen (it was used to test Tendermint)

More info could be found https://asatarin.github.io/testing-distributed-systems/

**Comment by yazzaoui** [comment]
On standby until we manage to get 100% compliant tendermint implementation
