### ISSUE TITLE
Research how to modularize Autonity Contract

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#387]
Investigate the feasibility of modularizing the Autonity Contract and splitting-it up in various contracts with something that would look like :
- stake model, bonding, delegation contract
- node permissioning contract
- governance contract
- Consensus mechanisms contract
- economic model (fee distribution; penalties/slashing; accountability) contract

Using either
- library contract ( `DELEGATECALL` )
- foreign contract (`CALL`)

**Comment by piersy** [comment]
@yazzaoui What's the problem description here, or what are the potential benefits to modularizing?

**Comment by yazzaoui** [comment]
Yes, I don't really know what modularizing could allow that can't be achieved with the current design. There are, however, from a pure software engineering point of view some reasons for why this could be wanted for the final state: better code organization, smaller contract size, composability, and code reuse.

**Comment by piersy** [comment]
@yazzaoui I think it is important to have a clear idea of what we are going to achieve through modularization. I would not embark on modularizing unless we had a clearly defined need for one of the following.
>better code organization, smaller contract size, composability, and code reuse

**Comment by yazzaoui** [comment]
Depreciated, closing.
