### ISSUE TITLE
Set up automated performance report generator

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#434]
# Problem

We need to start thinking about how to measure the performance of our system as we cannot allow performance regressions to go unnoticed or unresolved during the development cycle.

# Implementation

One idea is to extend python's e2e tests with benchmarking tests that could output a list of key metrics. 

Consider whether we can run this on every release and track the metrics in the release notes.

# Acceptance Criteria

- Define a set of key metrics
- Propose a way on how to track regressions.

**Comment by piersy** [comment]
Some work has been done on documenting the regression testing metrics here #503, the pr has been closed for now.

**Comment by yazzaoui** [comment]
Old issue, it's a good idea but no longer a priority, closing for now.

**Comment by JekaMas** [comment]
It's alive! OMG!

**Comment by yazzaoui** [comment]
Heya @JekaMas good to hear from you, our mainnet is (finally) coming soon :))
