### ISSUE TITLE
Request for documented process to remove a validator from a live network

### ISSUE THREAD

**Issue by p1747150-zz** [autonity/autonity#444]
# Problem

We need a documented process to remove a validator from a live network.

# Implementation

N/A

# Acceptance Criteria

Must be able to safely remove a validator without adversely impacting the live network.

# Notes

What should happen to any ETH owned by the Validator once it is removed?

# Future Steps

Verify the process.

**Comment by differentialderek** [comment]
The `removeUser()` function does the following:

1. Checks that the address is defined and that the user exists.
2. Removes `validators` and `stakeholders` from the `stakeholders` array.
3. Removes `validators` from the `validators` array.
4. Updates the `enodesWhiteList` list.
5. Updates the stake supply to reflect the user leaving.
6. Removes the user from the `users` map.
7. Emits a `RemoveUser()` event.

Needs addressed in other tickets:
1. #466: `removeUser()` should only execute after the end of a bonding period.
2. #467: What should be done with any ETH a validator owns once it's removed?
