### ISSUE TITLE
Spec for Delegation and Bonding

### ISSUE THREAD

**Issue by differentialderek** [autonity/autonity#460]
# Problem

In relation to Issue #458, we need to first make a spec for stake delegation delegation and bonding.

# Implementation

Define the spec for the functions `delegateStake()` and `reclaimStake()`, including the process for integration with things such as (un)bonding.

# Acceptance Criteria

Must include:
* `delegateStake()` function
* `reclaimStake()` function
* Checks relating to:
    * (un)bonding
    * committee/proposer selection mechanisms
    * `changeUserType()`

# Notes

None

# Future Steps

Continue with the next step of issue #458 (implementation).

**Comment by differentialderek** [comment]
# Spec for Delegation and Bonding
## New Functions
This PR will include five basic functions.
* `updateUserSelfStake()`
* `delegateStake()`
* `reclaimStake()`
* `bond()`
* `unbond()`

Each of these functions can only be executed (1) by the authority account, and (2) at the end of a bonding period, given in the public variable `bondingPeriod`.

### `updateUserSelfStake(_user : User, _selfStakeDifferential : uint256)`
* Takes a stakeholder or validator who wants to sell or buy stake. A negative
value of `_selfStakeDifferential` indicates the user wants to sell stake equal to
the absolute value of `_selfStakeDifferential`. A positive `_selfStakeDifferential`
indicates that the user wants to buy stake equal to the value of
`_selfStakeDifferential`.
* Checks `_user.userType == Stakeholder | Validator`.
* If `_selfStakeDifferential < 0`:
    * Checks `(-1) * _selfStakeDifferential < _user.stake`.
    * Updates `_user.selfStake = _user.selfStake + _selfStakeDifferential` to
    reflect the sell.
    * Transfers funds to `_user` from the authority account.
* If `_selfStakeDifferential >= 0`:
    * Checks `_selfStakeDifferential < userFunds`, where `userFunds` is the amount
    of tokens owned by `_user`.
    * Executes a transfer from `_user` to the authority account equal to
    `_selfStakeDifferential`.
    * Updates `_user.selfStake = _user.selfStake + _selfStakeDifferential`
    reflecting the purchase.

### `delegateStake(_user : User, _stakeDelegate : User, _delegatedStake : uint256)`
* Takes a user, the intended stake delegate, and the amount of stake the user
wishes to delegate. The user can only delegate undelegated stake, *i.e.* stake
stored by the variable `_user.selfStake`.
* Checks that both `_user.userType == stakeholder | validator` and
`_stakeDelegate.userType == validator`.
* Checks that `_delegatedStake >= 0`.
* Checks that `_user.selfStake >= _delegatedStake`.
* Updates `_user.selfStake = _user.selfStake - _delegatedStake`.
* Updates `_user.delegatedStake` to reflect the delegation.
* Updates `_stakeDelegate.delegatedStake` to reflect the delegation.
  * Both updates to the `delegatedStake` mapping will either update the
  `delegatedStake` balance from an existing user in the mapping or create a new
  key, value pair.

### `reclaimStake(_user : User, _stakeDelegate : User, _delegatedStake : uint256)`
* Takes a user `_user`, the delegating party, a user `_stakeDelegate`, the
delegated party, and an amount, `_delegatedStake`, of delegated stake.
* Checks that both `_user.userType == stakeholder | validator` and
`_stakeDelegate.userType == validator`.
* Checks that `_delegatedStake >= 0`.
* Checks that `_user` has indeed delegated `>= _delegatedStake` to `_delegatedUser`.
* Updates `_user.delegatedStake` and `_delegatedUser.delegatedStake` to reflect the reclamation,
and adds `_delegatedStake` to `_user.selfStake`.

### `bond(_participant : User, _newUserType : UserType, _requestedStake : uint256, mapping(_delegatedUser : User => _delegatedStake : uint256))`
* Takes a participant who wants to buy stake and become either a `stakeholder` or
a `validator`.
* Checks that `_newUserType` is either `Validator` or `Stakeholder`.
* Checks that the participant owns the sufficient funds to buy `_requestedStake`.
* Checks that the sum of the `_delegatedStake` values from the mapping is
less than or equal to the `_requestedStake`.
* Updates `_participant.userType` to the new type using the `changeUserType()` function.
* Transfers funds from `_participant` to the Authority Account reflecting the
purchase of stake tokens.
* Updates `participant.selfStake = _requestedStake`.
* For each `(_delegatedUser, _delegatedStake)` in the mapping, execute
`delegateStake(_participant, _delegatedUser, _delegatedStake)`.

### `unbond(_user: User)`
* Takes a stakeholder or validator who wants to sell their stake.
* Checks that `_user.userType` is `Validator` or `Stakeholder`.
* For each `(_stakeDelegate, _delegatedStake)` pair in the
`_user.delegatedStake` mapping, execute
`reclaimStake(_user, _stakeDelegate , _delegatedStake)`.
* Updates `_user.selfStake = 0`.
* Transfers funds from the Authority Account to `_user` to reflect the sell of
stake tokens.
* Changes user type to `Participant` by executing
`changeUserType(_user, Participant)`.

## Structural Shifts to the Autonity Contract
### Edit the `User` struct
* The `User` struct will change from having a `stake` entry to having two such
entries, `selfStake` and `delegatedStake`.
* Any function that interacts with the `User` struct will have to be changed,
including (but not necessarily limited to):
  * Functions that create new users.
  * Functions that use the `stake` parameter.
* Functions that create new users will have to be altered to reflect the change
in the `stake` parameter.
* Functions that use the `stake` parameter will instead use a `getUserStake()`
method which will return the total stake.
* The `delegatedStake` parameter will be of the form
`mapping(Bool => (mapping(User => uint256)))` where
`(0, (_delegatedUser, _delegatedStake))` indicates that `_user` has delegated
`_delegatedStake` to `_delegatedUser`, while
`(1, (_delegatingUser, _delegatedStake))` indicates that `_user` has been
delegated `_delegatedStake` by `_delegatingUser`.

### Functions that consider stake need to consider the sum total of the stake.
* Reward mechanisms relating to capping stake must prioritise `selfStake` over
`delegatedStake` so that a user cannot cut into another user's profits by
delegating stake to them (see comment on #458).

### Future Work
* Long range attacks are of concern in all proof-of-stake systems. This spec
doesn't treat long range attacks; those should be treated as future work.
* Should validators be able to choose if they are delegated stake or not?

**Comment by differentialderek** [comment]
The notion of `bond` and `unbond` as given in the above spec is not compatible with that outlined in the Yellow Paper. The previous spec treats `delegateStake` as what the Yellow Paper calls `bonding`, and `reclaimStake` as what the Yellow Paper calls `unbonding`. What the Yellow Paper calls `bonding` and `unbonding` is the notion of a participant becoming a validator or stakeholder by obtaining stake tokens, and then delegating them.

The following updates to the spec removes the composition of becoming a validator/stakeholder and delegation, leaving the functions `delegateStake()` and `reclaimStake()`. It renames those functions to `bondStake()` and `unbondStake()` to match terminology from the Yellow Paper.

# Updated Spec for Delegation and Bonding
## New Functions
This PR will include three essential functions.
* `bondStake()`
* `unbindingStake()`
* `unbondStake()`

It also includes one auxiliary function, which returns the total amount of stake a user owns.
* `selfStake()`

`bondStake()` and `unbindingStake()` can only be executed by the owner of the stake being (un)bonded, while `unbondStake()` is executed by the Authority Account after the `unbindingTime` has lapsed. The auxiliary function is public.

### `bondStake(_user : address, _stakeDelegate : address, _delegatedStake : uint256)`
* Takes a user address, the intended stake delegate, and the amount of stake the user
wishes to delegate. The user can only delegate undelegated stake, *i.e.* stake
stored by the variable `selfStake(_user)`.
* Checks that both the `userType` of `_user` is `Stakeholder` and
that the `userType` of `_stakeDelegate` is `Validator`.
* Checks that `_delegatedStake >= 0`.
* Checks that `_user.selfStake >= _delegatedStake`.
* Updates `_user.selfStake = _user.selfStake - _delegatedStake`.
* Updates `_user.delegatedStake` to reflect the delegation.
* Updates `_stakeDelegate.delegatedStake` to reflect the delegation.
  * Both updates to the `delegatedStake` mapping will either update the
  `delegatedStake` balance from an existing user in the mapping or create a new
  key, value pair.

### `unbindingStake(_user : address, _stakeDelegate : address, _delegatedStake : uint256)`
* Takes a user address `_user`, the delegating party, a user address `_stakeDelegate`, the
delegated party, and an amount, `_delegatedStake`, of delegated stake.
* Checks that both `_user.userType == stakeholder | validator` and
`_stakeDelegate.userType == validator`.
* Checks that `_delegatedStake >= 0`.
* Checks that `_user` has indeed delegated `>= _delegatedStake` to `_delegatedUser`.
* Adds the stake to be unbound to the `unbindingStake` contract state.

### `unbondStake()`
* When `unbindingTime` has elapsed since a user added stake to the `unbindingStake` contract state, updates `_user.delegatedStake` and `_delegatedUser.delegatedStake` to reflect the reclamation, and adds `_delegatedStake` to `_user.selfStake`.

## Global variables and contract states
* Global variable: `unbinding time`, that determines the amount of time that stake sits in the `unbindingStake` contract state before being reclaimed by the owner.
* Contract state: `ubindingStake`, of type `mapping (address => uint256)`, records the stake in the process of being unbound.
* Contract state: `delegatedStake`, of type
`mapping (address => mapping (address => uint256))` where
`delegatedStake[_delegating][_delegated][_amount]` indicates that `_delegating` has delegated
`_amount` to `_delegated`.
* Contract state: `delegatedList`, of type `mapping (address => mapping (bool => address[]))` used to facilitate searching `delegatedStake`. In this case, `delegatedList[_user1][true][_user2]` means that `_user1` has delegated stake to `_user2` and `delegatedList[_user1][false][_user2]` means that `_user1` has been delegated stake by `_user2`. (You can think of the `bool` as indicating the direction of an arrow, where `true` is `->` and `false` is `<-`.)

## Other functions affected
* `changeUserType()` will have to check that: 
    * a validator has no stake delegated to it when it downgrades to a stakeholder,
    * a stakeholder has no stake delegated elsewhere when it downgrades to a participant.

**Comment by JekaMas** [comment]
Lgtm

**Comment by piersy** [comment]
@differentialderek Hey I have some questions/suggestions

>Checks that both _user.userType == stakeholder | validator and
_stakeDelegate.userType == validator.

Shouldn't that be `_stakeDelegate.userType ==  stakeholder | validator` ? What if a user A delegates stake to a validator that then changes to be a stakeholder, user A would not then be able to reclaim their stake.

>Checks that _delegatedStake >= 0

We should probably not allow delegating zero stake, it seems like it would always be a mistake on the part of the delegator.

What would happen if a user that holds stake is removed?

**Comment by piersy** [comment]
It seems like their could be an issue with people unbonding and leaving not many validators remaining. Or when the system is initialised it sounds like (from reading the yellow paper) that no stake will at that point be bonded, and in this case if a single validator were able to bond stake before the others they would have total control of those blocks, they could mint eth into their account at that point.

**Comment by aneequesafdar** [comment]
I am not sure whether I am misunderstanding or this may be a mistake in the `bondStake()`:

> Checks that the delegating user is a stakeholder and the user being delegated stake is a validator (both `userType` of `_user` is `Stakeholder` and
that the `userType` of `_stakeDelegate` is `Validator`)

If we are putting a condition that the stake that is being delegated to is a validator (I understood that a validator is a stakeholder who has delegated stake, right?), then how does a new stakeholder become a validator? The first time someone tries to delegate stake to another stakeholder, this function will not let it do so and that stakeholder will never be able to become a validator. I also raise the question about how do I self delegate to become a validator, as per the current condition in the above scenario I will not be able to do that.

> Checks that the amount to be delegated is greater than or equal to zero (`_delegatedStake >= 0`)

Why are we allowing to stakeholder to delegate stake which is 0? it should be `_delegatedStake > 0` 

> Checks that the delegating user has enough stake to delegate (selfStake(_user) >= _delegatedStake)

This condition feels insufficient to me (also it should be > not >=), although the first condition is sufficient

> The user can only delegate undelegated stake, i.e. the user's total available stake minus that which has been delegated to it ( stake in users[_user].stake up to the amount selfStake(_user))

which make this condition redundant.

> Updates the global contract states bondedStake and bondedList to reflect the delegation and keep a record.

at this point, we should also be checking that the total bonded stake is <= total stake in the system as per the yellow paper constraints.

`initiateUnbondStake()`:

> Checks that the user is trying to reclaim (unbond) a positive amount of stake (_delegatedStake >= 0).

Again it should be > not >=.

> Global variable: unbindingTime, that determines the amount of time that stake sits in the unbindingStake contract state before being reclaimed by the owner.

How are we measuring time? Blocks?

**Comment by aneequesafdar** [comment]
@piersy Please read Assumption 3 in the Autonity yellow paper, which states that the size of the committee set must be at least 4 at any given height starting from 1.

**Comment by piersy** [comment]
@aneequesafdar Thanks for pointing this out, I'm going to have a solid read of the whole paper and then come back and have a look at this.

>@piersy Please read Assumption 3 in the Autonity yellow paper, which states that the size of the committee set must be at least 4 at any given height starting from 1.
