### ISSUE TITLE
Fix flaky eth/downloader tests

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#494]
# Problem

The following tests fail randomly.

TestBoundedHeavyForkedSync63Fast
TestBoundedHeavyForkedSync64Fast

We can see one of them failing [here](https://github.com/clearmatics/autonity/pull/491/checks?check_run_id=546047407) for a pull request that only added documentation.

I can see them both failing multiple times if i run
```
 go test -run "TestBoundedHeavyForkedSync63Fast|TestBoundedHeavyForkedSync64Fast" --count 100
```
From the `eth/downloader` dir.

# Acceptance Criteria

We should be able to run

```
go test -run "TestBoundedHeavyForkedSync63Fast|TestBoundedHeavyForkedSync64Fast" --count 500
```

Without any failures if those tests are passing on geth upstream. If not raise an issue on the go-ethereum repo.

**Comment by yazzaoui** [comment]
TestBoundedHeavyForkedSync63Fast and TestBoundedHeavyForkedSync64Fast are depreciated, closing.
