### ISSUE TITLE
helloworld demo error

### ISSUE THREAD

**Issue by tabbre-blockchain** [autonity/autonity#509]
# Problem

The Autonity helloworld demo throws up a web3.js error when submitting a sendTransaction
This is the first transaction on the newly started blockchain

I checked the docker log file, and this  shows that the autonity server didn't receive the tx request

Here's the action from the autonity cli
+++++++++++++++++++++

$ autonity attach http://0.0.0.0:8541
Welcome to the Autonity JavaScript console!

instance: Autonity/v0.4.0-c77532b6/linux-amd64/go1.13.9
coinbase: 0x850c1eb8d190e05845ad7f84ac95a318c8aab07f
at block: 0 (Thu, 01 Jan 1970 01:00:00 BST)
 datadir: /autonity-data
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.sendTransaction({from:eth.accounts[0], to:"0xf5bd521807791ad153b164a143368b04f923a21b", value: web3.toWei(1, "ether")})
Error: the autonity contract is not specified
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

> 
> eth.getBlock("latest").number
0

++++++++++++++++++++

**Comment by yazzaoui** [comment]
Apologies the documentation is lacking and outdated but we're working on that, I however just checked and the Helloword demo is correctly working with our latest release.

So it seems like your network was not correctly bootstrapped, did you run `docker-compose up -d` in the helloworld  directory ?

**Comment by aiman** [comment]
We have decided to drop the `helloworld` demo.
