### ISSUE TITLE
Add a glossary to the user documentation.

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#514]
# Problem
Some terms spefiic to the domain should be explained.

So far I have a list of these terms that call for a more detailed description.

```
Terms 
network
ethereum virtual machine
Autonity client
bytecode
ABI
Wei
address
enode
unix time
```

# Acceptance Criteria

Add a glossary to the user documentation, link all uses of the terms above to their glossary entries.

**Comment by cmjc** [comment]
Hi @piersy - terminology is defined in the Semantics Glossary, published out to https://vocab.autonity.io, the certificate of which is unfortunately still expired.

The currently published Semantica, certificate aside, is a stripped down version of the glossary to just the terms used in the FSSEA for SOW1, _but_ if you look in: [https://github.com/clearmatics/vocab-clearmatics-dot-com/tree/master/old-complete/html](https://github.com/clearmatics/vocab-clearmatics-dot-com/tree/master/old-complete/html) you will see I originally defined terms for EVM, EVM assembly, EVM code (I.e. byte code), virtual machine, process VM, p2p network, address, account, Autonity client, ABI - everything in your list except for Wei, node, unix time.

So, can I ask that you review those, raise any comments/change revision, new terms, etc - then I can look to review the currently published glossary and restore these missing terms, update them as review says required, add new terms etc.

I have again raised the expired certificate issue with ChatOps.
