### ISSUE TITLE
AIP 8 - Autonity Contract Callback Registry

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#522]
### Preamble 

```
AIP: 8
Title: Autonity Contract Callback Registry 
Author: YA
Type: ASC Standard Track
Category: Core 
Status: Draft
Created: 23-04-2020
```

### Motivation

Following a discussion I had with @maxrobot , it appeared that some contracts would greatly benefit from the ability to be reliably automatically called by the protocol itself, hence not relying on any external tool. 

We could have the Autonity Contract `finalize` function being directly used to perform these operations but having a generic solution would be much better, avoiding modifications of the Autonity Contract.

I found two technical challenges to tackle:
- Gas management.
- Re-entrency attacks with a pure layer 2 solution.

The following is a drafty proposal to conciliate those issues.  

### Specification

The Autonity Contract will implement the following functions :
```solidity
    function registerCallback(address contract, uint gasCost, uint period) payable external;
    function unregisterCallback(address contract) external;
```
- The message sender calling `registerCallback` will be saved as the callback calling address. 
- A positive amount of Eth would need to be transferred for paying the callback gas costs, e.g. `msg.value > 0`.    
- `period` is the number of blocks *after* which the callback will be called, `block.number + period` would be the first time the callback is invoked, `block.number + 2 x period` the second time, and so on.
- A subsequent call on `registerCallback` with the same message sender on a previously saved address will permit to top up the amount of saved funds and to update the gas cost. 
- If two differents callback calling address are registered with the same contract address then the callback will be called twice, that is to say, entries are unique per callback calling address. 
- The callback message gas price is equal to the current Autonity Contract minimum gas price value.
- Only the callback calling address can unregister a callback created by it.

A contract wishing to expose a function to be called back have to implement the following interface:
```solidity
interface AutonityCallback {
    function autonityCallback() external;
}
```

The Autonity Contract `finalize` will be extended to return a dynamic array of type:
```solidity
    struct callback {
        address contract;
        address caller;
        uint256 gasCost;
    }
``` 
- Layer 1 will call every function returned in this array using the returned informations.

### Implementation

- The Autonity contract may keep internally an array of :
```solidity 
    struct registeredCallback {
        callback cback;
        uint256 funds;
        uint creationBlock;
        uint period;
    }
``` 
- The Autonity contract may update `funds` internally before returning an entrie : ` funds = funds -  minGasPrice * gasCost` .
- If this amount is negative, the entry might be deleted. Non-used gas will be lost and might become part of the fee redistribution pool.
- If `funds = minGasPrice * gasCost`  this then leaves the possibility to create a callback for a single unique execution.
 
### Questions

- What to do with excess gas ? Having layer1 updating the layer2 entries with the exact amount of gas used would not be very performant.

**Comment by Jaime-Iglesias** [comment]
Looks like a very interesting proposal, what would be some of the uses-cases for this? 

Some questions:

Is there no risk with regards to the block size if the amount of registered callbacks becomes too big? 
Or since it's in the protocol itself it doesn't get affected?

> period is the number of blocks after which the callback will be called, block.number + period would be the first time the callback is invoked, block.number + 2 x period the second time, and so on. 

- Can we guarantee this ? 
- What would be the way the autonity contract handles a `callback` call reverting ? i.e if the autonity contract is traversing the `registeredCallbackArray` calling this functions and one of the call reverts.

> - The message sender calling registerCallback will be saved as the callback calling address.
> - A positive amount of Eth would need to be transferred for paying the callback gas costs, e.g. msg.value > 0.

Im not sure I understand this part, why do we need to register both the `msg.sender` and the `contract` ? can't we have the contracts themselves register ? i.e `msg.sender` = `contract` ?

**Comment by yazzaoui** [comment]
Thanks for the feedback Jaime.

> Looks like a very interesting proposal, what would be some of the uses-cases for this?

Ask Max he had some ideas, personally I can think for example of everything that depends on some oracle to trigger a state transition. 

> Is there no risk with regards to the block size if the amount of registered callbacks becomes too big?
> Or since it's in the protocol itself it doesn't get affected?

Blocks don't contain the full list of saved callbacks, the data is saved in the local database, so it's not really a problem.
 
> > period is the number of blocks after which the callback will be called, block.number + period would be the first time the callback is invoked, block.number + 2 x period the second time, and so on.
> 
> * Can we guarantee this ?

Yes, that's the purpose of this mechanism, you just don't have control on `block.number` as you don't know when the transaction registering the callback will be mined. If you think it's a problem we can add a new parameter `blockStart` so you have a very precise control on the block height when the callbacks are executed.

> * What would be the way the autonity contract handles a `callback` call reverting ? i.e if the autonity contract is traversing the `registeredCallbackArray` calling this functions and one of the call reverts.

Important to note that the Autonity Contract itself is not calling those contracts directly, that's being done at layer1 so you can have control on `msg.sender` and avoid reentrency attacks. If a call reverts, the gas is still being taken off the saved funds to ensure that it won't continue forever.  The other callback are called anyway.

> Im not sure I understand this part, why do we need to register both the `msg.sender` and the `contract` ? can't we have the contracts themselves register ? i.e `msg.sender` = `contract` ?

The scheme allows contracts registering themselves and `msg.sender = contract`, but it allows as well to have a different `msg.sender`.

**Comment by Jaime-Iglesias** [comment]
> Important to note that the Autonity Contract itself is not calling those contracts directly, that's being done at layer1 so you can have control on msg.sender and avoid reentrency attacks. If a call reverts, the gas is still being taken off the saved funds to ensure that it won't continue forever. The other callback are called anyway.

I see, I think I missunderstood the mechanism - so, correct me if im wrong, the Autonity contract only has a register of "transactions that need to be executed periodically" and then that registry is read by _somone_ and signed and executed by _who_ ?

**Comment by yazzaoui** [comment]
> the Autonity contract only has a register of "transactions that need to be executed periodically" and then that registry is read by _someone_ and each transaction signed and executed by _who_ ?

Yes, so _someone_ is the Autonity protocol and there are no transactions associated to those calls. It is already the case for fee redistribution with the Autonity Contract `finalize` function being called every block after processing transactions in this block.
 
We are in full control of the client (layer 1), so we can bypass the requirement to have a transaction in order to call the evm.

**Comment by Jaime-Iglesias** [comment]
> > the Autonity contract only has a register of "transactions that need to be executed periodically" and then that registry is read by _someone_ and each transaction signed and executed by _who_ ?
> 
> Yes, so _someone_ is the Autonity protocol and there are no transactions associated to those calls. It is already the case for fee redistribution with the Autonity Contract `finalize` function being called every block after processing transactions in this block.
> 
> We are in full control of the client (layer 1), so we can bypass the requirement to have a transaction in order to call the evm.

ahhh, I understand now - are these state transitions (done without transaction) queriable to the layer 2? i.e can a user see through it's transaction broker that these calls were made, just like you can query the transactions on a block?

Furthermore, do we expect to limit the things users can execute on these callbacks? Like you said, a reentrancy attack could be a possibility - perhaps we could limit the opcodes that can be executed in a callback - i.e make sure a  `selfdestruct` or ` delegatecall` is unreachable, although this will add extra complexity to the thing.

My concern about my questions  is rather - if, lets say,  you could achieve the same result with a `callback` mechanism through the protocol, why would you choose to create a transaction ?

**Comment by JekaMas** [comment]
I think `registerCallback` could be extended with one parameter more TTL, time to live or maximum number of calls.
