### ISSUE TITLE
Remove un-needed difficulty check from VerifySeal

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#568]
# Problem

VerifySeal (below) checks the block difficulty, but it shouldn't.
https://github.com/clearmatics/autonity/blob/5bf80af7077552bbb07fdcbdd9ad1bb0a7516526/consensus/tendermint/backend/engine.go#L280-L294

According to the interface definition, verify seal should just be checking the signature.
https://github.com/clearmatics/autonity/blob/5bf80af7077552bbb07fdcbdd9ad1bb0a7516526/consensus/consensus.go#L79-L81

Validating other field values should be done in VerifyHeader.
https://github.com/clearmatics/autonity/blob/5bf80af7077552bbb07fdcbdd9ad1bb0a7516526/consensus/consensus.go#L64-L67

# Acceptance Criteria

Only perform signature verification in VerifySeal

**Comment by aneequesafdar** [comment]
something for #561

**Comment by piersy** [comment]
@aneequesafdar I didn't feel that this ticket met the conditions to be part of #561.

It's not changing interfaces, and its not dealing with entanglement, so the only thing it could be doing is removing unneeded complexity. You could argue that it is doing that, but the reduction in complexity is so minor I don't think it really qualifies.

**Comment by piersy** [comment]
Discussed with the team, we are happy to remove the difficulty check from VerifySeal.
