### ISSUE TITLE
Remove the les package

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#583]
# Problem

This ticket relates to #561 

We are not currently using or maintaining the `les` package, yet we retain the code for the package.

Why is this a problem?

Having unneeded unmaintained code slows us all down as developers, it is the opposite of being lean.

Having extra unneeded code wastes developer time because we end up navigating through code that if it were not there we would not need to do. The unused code shows up in searches, cluttering our view of and damaging our potential to understand the remaining code.

Not only that it slows down builds, slows down IDE indexing/searching, slows down tests, which all contribute to slowing us down as developers.

Finally it runs the risk of actually being run in production, and is hence another source of bugs in the system.

# Implementation

Delete les and remove references to it from other packages

it is currently being used in these files
```
cmd/autonity/main.go
cmd/utils/flags.go
cmd/faucet/faucet.go
ethstats/ethstats.go
```

# Acceptance Criteria

The les and light packages dont exist.

**Comment by aiman** [comment]
We decided to remove access to `les` but leave it in place to simplify upstream merge, or at least to have option in future to re-integrate easily.
