### ISSUE TITLE
Fix goroutine leaks in go-ethereum

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#605]
# Problem

We suffer from many goroutine leaks in our tests. The root cause of this is because we are starting, stopping and then starting nodes within a single process in our end to end tests framework, and nodes are not properly clearing up their go-routines when they are stopped. The lack of correct cleanup is something we have inherited from the go-ethereum project. The go-ethereum project does not have any tests where they start, stop and then start nodes again so the leaked go-routines are not a problem for them (they may not even be aware of their existence). To date we have been fixing these in our own codebase, but this is not an optimal solution for 2 reasons.

* Fixing these leaks requires tweaking code deep inside many go-ethereum packages, which we could otherwise leave alone. Thus being a big source of conflicts when we update from go-ethereum.
* When we do update it is quite likely that the go-ethereum team will have introduced new go-routine leaks, which we then need to fix.

This ticket is intended to cover the work of fixing the go-routine leaks in the go-ethereum project and making the go-ethereum team aware of the problem so that we do not have to keep on fixing these leaks.

This will be a beneficial change for the go-ethereum project as many strange bugs can occur in production code with leaked goroutines and I'm sure we are not the only fork encountering these problems.

# Acceptance Criteria

Fix all the leaked go-routines in the go-ethereum project

**Comment by yazzaoui** [comment]
I couldn't pick up any race condition using `go test -race`. Closing this one for now.
