### ISSUE TITLE
Remove function name from first line of function comment in Autonity.sol

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#608]
# Problem

Relates to #561 

We seem to start all function comments with the function name on a line by itself. This doesn't appear to be part of any coding standard or comment style used for solidity comments. At best it is superfluous noise that the reader will have to filter out, at worst the name will fall out of sync with the function name and lead to confusion.
```
    /*
    * changeUserType
    * Change user status
    */
    function changeUserType( address _address , UserType newUserType ) public onlyOperator(msg.sender) {

```
# Acceptance Criteria

The first line of function comments to not solely contain the function name.

**Comment by aiman** [comment]
Since switch to NatSpec we don't have this issue any more.
