### ISSUE TITLE
CRIT log for TestTendermintOneMalicious

### ISSUE THREAD

**Issue by IronGauntlets** [autonity/autonity#629]
# Problem

During [this](https://github.com/clearmatics/autonity/runs/915618446) github action run for `TestTendermintOneMalicious` the following `CRITICAL` error occurred:

```
CRIT [07-27|17:11:12.094] Failed to store the transaction index tail err="leveldb: closed"
FAIL	github.com/clearmatics/autonity/consensus/test	40.198s
FAIL
```

Seems like the db was closed before it should have.

# Acceptance Criteria

Since we cannot reproduce this bug easily the PR must show how this occurred and make clear that this cannot happen again.

**Comment by Jason-Zhangxin-Chen** [comment]
Since this test case is no longer living in the integration test framework, more over that we are droping the legacy integration test framework, and moving the tests under it to the e2e test framework, thus we have to close this issue.
