### ISSUE TITLE
Intermittent failure in TestTransactionPoolUnderpricing

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#642]
# Problem
The following error was seen in the following run.

https://github.com/clearmatics/autonity/runs/972042470?check_suite_focus=true

```
--- FAIL: TestTransactionPoolUnderpricing (0.05s)
##[error]    tx_pool_test.go:1416: pending transactions mismatched: have 1, want 2
```

# Acceptance Criteria

Since this happens intermittently, it will be hard to verify the fix therefore the PR should make it clear what the problem was and how it has been fixed.

**Comment by aiman** [comment]
Let's try to reproduce this issue.

**Comment by lorenzo-dev1** [comment]
Running the test 1000 times did not yield any failures, closing as not an issue anymore.
