### ISSUE TITLE
upon_condition_test.go uses randomised variables but lacks mechanism to reproduce failed test cases

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#659]
# Problem
 As an example.

The following blocks show the randomly selected variables for a single test case.
https://github.com/clearmatics/autonity/blob/6b7fa2f565241b35121b0c5aba6fab9f8925e39e/consensus/tendermint/core/upon_condition_test.go#L435-L436
https://github.com/clearmatics/autonity/blob/6b7fa2f565241b35121b0c5aba6fab9f8925e39e/consensus/tendermint/core/upon_condition_test.go#L563-L568

They are:
committeeSet (4-99) range of 96 possible values
currentHeight  (1-100) range of 100 possible values
currentRound (4-99) range of 96 possible values
proposalValidRound (4-99) range of 96 possible values
clientLockedRound ((-1)-100) range of 101 possible values

So there are potentially `96*100*96*96*101 = 8935833600` (roughly 9 billion) different random states that could be generated here. If you don't know what the random variables were when the test failed, and the failure was specific to that selection of variables it will be impossible to recreate the failure. 

# Implementation

Ensure that the seed used to initialise rand is printed out in any test failure. That way you can then hardcode the seed to reproduce the observed failure.

# Acceptance Criteria
When tests fail that were run with randomly selected variables, it must be possible to easily reproduce the failing selection of variables.

**Comment by Jason-Zhangxin-Chen** [comment]
This issue should be closed by PR: https://github.com/autonity/autonity/pull/950.
