### ISSUE TITLE
The helloworld genesis file defines only one network member

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#663]
# Problem

The helloworld example fires up 5 nodes but actually only the first node is permissioned (as a validator) to be part of the network in the genesis file, this means that the other 4 are not able to connect and sync, meaning that they will never progress beyond block 0.
 
We should probably set up a genesis file such that there are some validators and some participants, to provide a more realistic and varied configuration.

# Implementation

Constructing genesis files by hand is error prone and time consuming so I would like to use gengen to generate the genesis on the fly, this should lessen the chance that the genesis becomes invalid if we change the definition and forget to update it. It also could provide for easy user customisation of the network members.

# Acceptance Criteria

All nodes started up as part of autonity helloworld should be permissioned to be part of the network.

**Comment by aiman** [comment]
The helloworld has been removed.
