### ISSUE TITLE
Docker e2e tests for TC-19 are not stable

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#697]
#Problem

The tests failed in this run linked below

https://github.com/clearmatics/autonity/runs/1215675810?check_suite_focus=true

I'm unable to upload the logs because the file is larger than 10mb.

**Comment by piersy** [comment]
@Jason This is happening again here is the failed run link

https://github.com/clearmatics/autonity/runs/1463876861?check_suite_focus=true

**Comment by Jason-Zhangxin-Chen** [comment]
> @jason This is happening again here is the failed run link
> 
> https://github.com/clearmatics/autonity/runs/1463876861?check_suite_focus=true

Same scenario happens, since we haven't merged this PR: https://github.com/clearmatics/autonity/pull/700
