### ISSUE TITLE
Separate genesis block config and chain config.

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#704]
Problem

The genesis file contains a json structure that contains both config that define the initial block and also config that controls how the autonity client behaves.

Ethereum historically separated these two types of config in the following way in the genesis file.
```
{
  "config": {
    ...  // Config that controls how the client behaves
  },
  ... // Fields that contribute to the genesis block.
}
```
Our autonity additions have broken this separation.

```
{
  "config": {
    ...  // Config that controls how the client behaves
    "autonityContract": {
      ... // Config that contributes to the genesis block
    }
  },
  ... // Fields that contribute to the genesis block.
}
```

So in order to maintain the separation between config that contributes to the genesis block and config that affects behaviour of the autonity client we should move the `autonityContract` field out of `config`

E.g:
```
{
  "config": {
    ...  // Config that controls how the client behaves
  },
  "autonityContract": {
    ... // Config that contributes to the genesis block
  }
  ... // Fields that contribute to the genesis block.
}
```

# Acceptance Criteria

There should be a clean separation between config that feeds into the genesis block and config that affects behaviour of the autonity client.

**Comment by donmiguelenriquez** [comment]
If the idea is to follow the Ethereum default, would not be better to use the extraData field for the autonityContract instead of adding a new field to the root of the genesis file ?

**Comment by aiman** [comment]
Thank you for the discussion. We have decided to retain the current structure of the genesis file because it's good enough in terms of organization.
