### ISSUE TITLE
To fix 10 skiped unstable testcases on CI pipe line of local e2e test.

### ISSUE THREAD

**Issue by Jason-Zhangxin-Chen** [autonity/autonity#711]
After the improvement and bug fixing on the local e2e test framework, we still have belwo 10 cases were skipp to be fixed.
/Tendermint TestContractUpgradeSeveralUpgrades test
Case got 40 timeout on CI: consensus core handler: Failed to validate message.

/Tendermint TestContractUpgradeSeveralUpgrades test
Flaky due to 40m timeout: Failed to validate message

/ Tendermint TestContractUpgradeSeveralUpgradesOnStarTopology test
Flaky due to 40m timeout: Failed to validate message

/ Tendermint TestTendermintMemoryLeak test

/ Tendermint TestTendermintStartStopFPlusTwoNodes test
It's flaky due to 40m timeout issue.

/ Tendermint TestTendermintStartStopAllNodes test
Skip test due to 40m timeout issue

/ Tendermint TestTendermintStarOverParticipantSuccess test
case is still flaky dueto 40ms timeout, consensus core handler: Failed to validate message

/ TestTendermintStartStopAllNodes
case is flaky due to 40m timeouts.
https://github.com/clearmatics/autonity/runs/1315225586?check_suite_focus=true

/ TestTendermintExternalUser
case is flaky due to go routine leak, see logs:
https://github.com/clearmatics/autonity/runs/1331045393?check_suite_focus=true

/ TestTendermintStartStopAllNodes
case is flaky due to 40m timeout happens sometime.
https://github.com/clearmatics/autonity/runs/1331510716?check_suite_focus=true

**Comment by lorenzo-dev1** [comment]
@Jason-Zhangxin-Chen do you think these issues are still valid?

**Comment by Jason-Zhangxin-Chen** [comment]
We can close it now.
