### ISSUE TITLE
TestTendermintStartStopFPlusOneNodes times out

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#749]
# Problem

The test times out and, on investigation it seems that messages are being sent but that no round or height progress is being made. This could be as a result of us not storing state  see - #84 or it could be something else, I can't understand why the other start stop tests seem to still work where this one fails.

# Acceptance Criteria

Either fix this test or rewrite it with the new testing framework  #649

**Comment by yazzaoui** [comment]
Depreciated as this test was removed, closing.
