### ISSUE TITLE
Non-autonity nodes trying to connect with autonity nodes

### ISSUE THREAD

**Issue by raj-shekhar1** [autonity/autonity#791]
### Description
The non-autonity nodes currently try to connect with the autonity-nodes and fails with below Error messages

```
DEBUG[03-15|18:00:30.117] Adding p2p peer                          peercount=19 id=ae586ed09cff64ef conn=dyndial            addr=202.61.241.58:30303               **name=besu/v23.1.1/linux-x...**
ERROR[03-15|18:00:30.117] Snapshot extension registration failed   peer=ae586ed0   err="peer connected on snap without compatible eth support"
DEBUG[03-15|18:00:30.117] Removing p2p peer 
```
An average of less than 10 connection attempts per second from non-autonity nodes, essentially the eth wire protocol handshake didn't succeed which is causing the snap sub-protocol to reject the connection as expected.

### System Information

Autonity Version: `v0.10.1`

### How to Reproduce

1. Deploy a node on Piccadilly network
2. Check the logs for "Snapshot extension registration failed   peer=ae586ed0   err="peer connected on snap without compatible eth support"

### Expected Behaviour

Non autonity nodes should not try to connect to autonity nodes by default.

**Comment by raj-shekhar1** [comment]
@cmjc , can we please add this as a known issue in the [docs](https://docs.autonity.org/issues/).

**Comment by cmjc** [comment]
I've created issues to track this here:

- Known issues: add issue for Non-autonity nodes trying to connect: https://github.com/autonity/docs.autonity.org/issues/48 
- Known issues: review for next documentation release: https://github.com/autonity/docs.autonity.org/issues/49

**Comment by cmjc** [comment]
PR created to add the known issue to the docs: https://github.com/autonity/docs.autonity.org/pull/50
