### ISSUE TITLE
In the readme file : redirect to wrong link

### ISSUE THREAD

**Issue by jfaiza** [autonity/autonity#794]
### Description
In the readme file, the "Run Autonity" link is not correct it generates an error
![image](https://user-images.githubusercontent.com/79405564/230808773-081fb30f-9c1e-4249-bbcf-b55d5750ab6a.png)

### Actual Behaviour
>> Error:
![image](https://user-images.githubusercontent.com/79405564/230808714-8fd9feee-8458-4d31-b2d0-069ea93347f2.png)

**Comment by cmjc** [comment]
Thanks for finding and reporting this broken link in the README documentation @jfaiza .

Fixed in commit cb2c56a2f87ff1695bb5026ef80c3c3435884f38 and added to existing PR on README https://github.com/autonity/autonity/pull/790.
