### ISSUE TITLE
"Issues"/"Report an issue with the docs" : Error in redirect

### ISSUE THREAD

**Issue by jfaiza** [autonity/autonity#795]
### Description

Error in redirect when we try the button "open" of "Report an issue with the docs " .

![image](https://user-images.githubusercontent.com/79405564/230809980-5db649f7-78b5-4fe5-9946-017ab161b45a.png)

### Actual Behaviour
Page not found :

![image](https://user-images.githubusercontent.com/79405564/230810052-892cd51b-8543-48ad-9bc2-3f1398b24a20.png)

**Comment by cmjc** [comment]
Thanks for finding and reporting this bug  @jfaiza .

The cause is a broken link in the issue template config https://github.com/autonity/autonity/blob/develop/.github/ISSUE_TEMPLATE/config.yml.

PR created for this here: https://github.com/autonity/autonity/pull/796
