### ISSUE TITLE
accountability : add support for PVN and PVO e2e tests

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#799]
PVN and PVO e2e testing is currently disabled as those tests can not be supported with the current testing framework.
Indeed, with only one byzantine validator one cannot produce these kind of faults without triggering PN and PO faults as well.

To fix that, we'll need to add support for multiple byzantine validators.

**Comment by Jason-Zhangxin-Chen** [comment]
To be closed by PR: https://github.com/autonity/autonity/pull/950 via commit https://github.com/autonity/autonity/pull/950/commits/318bdfbb495225f47d21ae628184a28f2e6a790e

**Comment by lorenzo-dev1** [comment]
Thanks to @Jason-Zhangxin-Chen we now have the collusion framework, so this can be closed.
