### ISSUE TITLE
Adopt computing terminology for precision and scale factor

### ISSUE THREAD

**Issue by aiman** [autonity/autonity#811]
We should adopt computing terminology for terms like precision, scale, and scale factor. These terms have a long history of usage in IT, such as in databases.

Although there are some variations depending on context, in general:

- _precision_: maximum number of significant digits in a numerical representation
- _scale_: the number of digits to the right of the decimal point
- _scale factor_: a multiplier used to represent a number on a different scale

In the Solidity code, there are several places where a variable is named _precision_ when is actually a _scale factor_. For example:

| Source             | Variable                             |
| ------------------ | ------------------------------------ |
| Accountability.sol | `SLASHING_RATE_PRECISION = 10_000`   |
| Liquid.sol         | `COMMISSION_RATE_PRECISION = 10_000` |
| Oracle.sol         | `PRECISION = 10_000_000`             |

It would be good to rename such usage to reduce confusion and enable us to use the terms consistently and correctly.

References:

- [Wikipedia: Scale Factor](<https://en.wikipedia.org/wiki/Scale_factor_(computer_science)>)
- [IBM Informix Fixed-precision numbers: DECIMAL and MONEY](https://www.ibm.com/docs/en/informix-servers/14.10?topic=types-fixed-precision-numbers-decimal-money)

**Comment by yazzaoui** [comment]
Thanks @aiman I believe adopting "decimals" in place of "Scale Factor" in our Solidity code aligns more with how the term is understood in the context of EVM development, what do you think?

**Comment by aiman** [comment]
@yazzaoui I don't think "decimals" is the right term to replace what is currently called `PRECISION` in some of the code, which is essentially `10**scale`, rather conventionally "decimals" is shorthand for "decimal places". So in this terminology it is the `scale` itself. For example one would say "The rate is at four decimals" or "The rate is at four decimal places".

**Comment by yazzaoui** [comment]
I think there is a misunderstanding I was thinking of replacing the `getPrecision` function currently returning the scale factor with `getDecimals` returning the scale.

**Comment by aiman** [comment]
In that case, yes "decimals" is common usage, and an acceptable term for numeric "scale", such as in the optional ERC-20 function `decimals()` (already implemented by `Autonity.sol` and `Liquid.sol`). 

> I was thinking of replacing the `getPrecision` function currently returning the scale factor with `getDecimals` returning the scale.

The issue is more about the general usage of the term "precision", not only in the Oracle function `getPrecision`, but also in the `internal` as well as `public` variables with some examples given above. Which is why I wrote:

> In the Solidity code, there are several places where a variable is named _precision_ when is actually a _scale factor_ ... It would be good to rename such usage to reduce confusion and enable us to use the terms consistently and correctly.

So the proposal to replace `getPrecision` with `getDecimals` is fine, but doesn't seem to address the problem of variables called "precision" that should be called something better like "scale factor".

Now if there is a better term than "scale factor" we can go with that, but I couldn't think of one!

**Comment by lorenzo-dev1** [comment]
All the code has been refactored to adhere to more precise terminology. I think this can be closed if we are all happy with the outcome @aiman @yazzaoui

**Comment by aiman** [comment]
Thanks @lorenzo-dev1 . Although I haven't reviewed all the code that was changed, but just from several spot checks, it looks to me a lot more sensible and consistent.

**Comment by lorenzo-dev1** [comment]
Great, closing as completed then!
