### ISSUE TITLE
Chunked events always fail in case first `chunkId = 1`

### ISSUE THREAD

**Issue by tbssajal** [autonity/autonity#840]
In `Accountability.sol`, while handling chunked events, starting from both 0 or 1 as `chunkId` is allowed. If the events are sent starting from `chunkId = 1`, the `reporterChunksMap` will have only `rawProof` and `chunkId` stored and finally it will fail with `offender mismatch` error in case of valid proof. So effectively chunked events have to start with `chunkId = 0` or it will fail anyway.
```
function _storeChunk(Event memory _event) internal returns (bool){
    // saving a chunk with id 0 will reset the local store
    if (_event.chunkId == 0) {
        reporterChunksMap[msg.sender] = _event;
        return false;
    }
    require(reporterChunksMap[msg.sender].chunkId + 1 == _event.chunkId, "chunks must be contiguous");
    BytesLib.concatStorage(reporterChunksMap[msg.sender].rawProof, _event.rawProof);
    reporterChunksMap[msg.sender].chunkId += 1;
    // return true if it's the final chunk, to be processed immediately
    return _event.chunkId + 1 == _event.chunks;
}
```

**Comment by lorenzo-dev1** [comment]
Closing since we removed the chunked events logic
