### ISSUE TITLE
Implement "Atomic Protocol Contract Upgrades"

### ISSUE THREAD

**Issue by lorenzo-dev1** [autonity/autonity#853]
### Description

Currently only the Autonity Contract is upgradable, using a native protocol which replaces the contract bytecode in the EVM.

We want to have a uniform way to upgrade all the protocol contracts. 

### Rationale

Upgrading contracts is necessary to easily update logic and fix bugs.

### Implementation

This could be subject to change as we dive deeper into the topic. 

The current idea is to generalize the approach used by the AC by using a precompiled contract. This would allow us to change the bytecode section of any protocol contract with the updated version. Care needs to be taken to ensure that only allowed entities can use this workflow (e.g. authorization should be put in place correctly).

Additionally for the LNTN contracts we want to decouple state and logic. We want to have multiple (1 for each validator) proxy contracts storing the state, and only a single LNTN contract "logic" implementation. The "logic" contract will be the one being updated when there is a LNTN contract upgrade, while the state ones will remain untouched.

**Comment by lorenzo-dev1** [comment]
note: written in pair-work with @vpiyush.

We have two potential options for our contract upgrade mechanism. Following is their description alongside with pros and cons.

### Option 1: In-Place Mechanism (EVM.Replace)

Bytecode of the contract is replace in-place using a native upgrade mechanism.

**Pros:**
- **Lower Gas Fees**. An additional level of indirection increments the gas expenditure. See our measurements in the table below.

 | Bytes    | Indirect     | Direct    | Diff    | % Increase |
|------------|--------------|-------------|--------| --------------- |  
| 1024     | 24642151     | 24600268  | 41883   | 0.17% |
| 300      | 7350193      | 7338088   | 12105   | 0.16% |
| uint256  | 48671        | 43724     | 4947    | 11% |

- Allows fixing of contracts even if they are not designed to be upgreadable.

**Cons:**
- Less transparent, breaking the general assumption of contract immutability.
    - **Mitigation:** Introduce the concept of mutable/immutable contracts and allow in-place upgrades only for mutable ones.
- Requires updates to tools such as block explorers to accommodate this new upgrade mechanism.
- This approach is new and not battle-tested, necessitating thorough investigation.
- Risk of processing transactions intended for the old implementation when the upgrade happens.
    - **Mitigation:** Introduce an additional identifier (a version/code hash) alongside the contract address when sending a transaction.

### Option 2: Standard Proxy Contract Update

**Pros:**
- Battle-tested, trusted, and widely used by the community.

**Cons:**
- Slightly higher gas costs when invoking APIs.

### Other Considerations

**Who can initiate an upgrade?**
- `OnlyOperator`: we propose that only the operator should have the privilege to initiate an upgrade transaction. Another option could be using the modifier `OnlyProtocol`, however we argue that contract upgrades can always be performed via client software upgrades (regardless of the modifier used). Thus the `OnlyOperator` is more permissive (allows upgrade both via an operator transaction AND via a client software upgrade).

**Upgrade Process:**
- It is assumed that a governance mechanism exists for deciding on upgrades.
- Upon decision, the operator:
    - Deploys the new implementation.
    - Sends an upgrade transaction.
    - Depending on the upgrade type:
        - **Feature/non-critical upgrade:** Wait for a set number of epochs (a protocol parameter) before applying the upgrade, giving everyone a fair chance to unbond funds if they disagree with the changes.
        - **Critical upgrade:** If there's a bug posing a serious threat, such as potential loss of funds, the upgrade is applied immediately to mitigate any severe consequences.

**Comment by lorenzo-dev1** [comment]
Actually by doing some more digging, it seems to me that it is not an assumption that smart contracts are immutable on Ethereum. There can indeed be [metamorphic contracts](https://proxies.yacademy.dev/pages/proxies-list/#metamorphic-contracts). Those contracts are upgraded by SELFDESTRUCTing the contract, and using CREATE2 to deploy a new contract at the same address.

**Comment by cmjc** [comment]
Yes, it's a way but with vulnerabilities and I remember a lot of discussion on that at the time. could be an audit issue, this is old, but see https://www.certik.com/resources/blog/introducing-certik's-create2-audit-tool

**Comment by lorenzo-dev1** [comment]
Yeah it doesn't seem the best idea to me how Ethereum implemented it, since the detection of metamorphic contracts needs to be done [via heuristics](https://a16zcrypto.com/posts/article/metamorphic-smart-contract-detector-tool/).

I am actually starting to think that having an in-place native upgrade mechanism + a clear distinction between mutable and immutable contracts would be better than having metamorphic contracts. We could even remove CREATE2 unless it has other uses in which we are interested in.

**Comment by lorenzo-dev1** [comment]
This has been successfully implemented, closing.
