### ISSUE TITLE
Quorum Calculation Bug

### ISSUE THREAD

**Issue by tbssajal** [autonity/autonity#854]
From the [code](https://github.com/autonity/autonity/blob/develop/consensus/tendermint/bft/thresholds.go) it looks like quorum is calculated by the following formula:

$Q = ceil(\frac{2N}{3})$

Where I think it should be calculated with the following:

$Q^\prime = N-F$

where, fault tolerance threshold, $F = floor(\frac{N-1}{3})$[^F]

If my assumption about quorum calculation is wrong then there is no issue. But I think it should be $N-F$ indicating participation of all honest/correct nodes. The issue is as follows:
There are three cases possible for N:

1. $N = 3F+1$
2. $N = 3F + 2$
3. $N = 3F + 3$

For first two cases $Q = Q^\prime$ but for third case $Q = 2F + 2$ where $Q^\prime = 2F + 3$, so $Q < Q^\prime$. So all honest nodes don't need to participate to reach quorum in this case.

[^F]: We implemented the same [here](https://github.com/autonity/autonity/blob/develop/consensus/tendermint/bft/thresholds.go#L17)

**Comment by yazzaoui** [comment]
$Q = N - F$ is wrong in the general case, the two fundamental assumptions are the following:

A) There must still be a quorum without the faulty nodes:
$$N - F \ge Q$$

B) Two quorums interests at least in one honest node:
$$2Q - N > F$$

I let you derive them to retrieve $Q = ceil(\frac{2N}{3})$

**Comment by tbssajal** [comment]
Yeah it makes sense, got it. Thanks for clearing up!

**Comment by lorenzo-dev1** [comment]
I cannot derive $Q = ceil(\frac{2N}{3})$.

If we put ourselves in the worst case scenario $N - F = Q$ -----> $F= N-Q$. 

Substituting then in the second equation $2Q - N > N - Q$ -----> $Q > \frac{2N}{3}$

So I would say that:
$$Q = ceil(\frac{2N}{3} + 1)$$

That's because a +1 needs to be applied if 2N is perfectly dividable by 3 (without mod)

**Comment by tbssajal** [comment]
I was doing something like this:
We know $F < N/3$
So $N+F < 4N/3$
As $2Q > N+F$ we can write $2Q \ge 4N/3$ so $Q \ge 2N/3$

Again for $N-F \ge Q$
we can use $F < N/3$ so $N-F > 2N/3$
I don't get much from here except $N-F \ge Q \ge 2N/3$ or $2N/3 \ge Q$

**Comment by lorenzo-dev1** [comment]
I don't know if starting from $F < N/3$ is a correct approach, because that should be a consequence of the two assumptions that @yazzaoui wrote

**Comment by tbssajal** [comment]
I thought it was also a base assumption, although I could be wrong.

**Comment by tbssajal** [comment]
Actually we can derive $F < N/3$ from here:
We have
$N-F \ge Q$
and
$2Q - N > F$ or $Q > (N+F)/2$
So $N-F \ge Q > (N+F)/2$
or $N-F > (N+F)/2$ and so $F < N/3$

**Comment by lorenzo-dev1** [comment]
Why not:
$N-F \ge Q > (N+F)/2$
or, $N-F \ge (N+F)/2$
or, $F \le N/3$
