### ISSUE TITLE
Bonding to Jailed Validator

### ISSUE THREAD

**Issue by tbssajal** [autonity/autonity#895]
Not sure if it is a bug or intentional, but when applying bonding at epoch end, we apply all the pending bonding request. When receiving a bonding request we check if the validator was active or not and accept the request only if the validator was active. But the validator can be jailed after the bonding request is accepted and before the bonding is applied. In that case, I think we should check if the validator is still active before applying bonding. From the point of view of the delegator, he would not want to bond to a jailed validator and he may not know that the validator was going to be jailed when requesting for bonding, if he only listens to `SlashingEvent`. I think we can reject bonding request at `_applyBonding` function if the validator is jailed.

**Comment by yazzaoui** [comment]
I see, but what if the validator becomes `paused` too? Should we just generalize it to only execute `_applyBonding` if state == active ?

**Comment by tbssajal** [comment]
> Should we just generalize it to only execute _applyBonding if state == active ?

I support that. Even if being paused is not a punishment, it is intentional and delegator won't be able to use his stakes for some epoch. I vote in support.

**Comment by yazzaoui** [comment]
Ok, let's do that unless someone has any objections.
