### ISSUE TITLE
Unknown Prometheus metric type *metrics.StandardBufferedGauge

### ISSUE THREAD

**Issue by ThomasBlock** [autonity/autonity#898]
Prometheus is an important monitoring tool.
It can be activated via `--metrics --metrics.addr "0.0.0.0" --metrics.port 1234` 
and accessed via `http://hostname:1234/debug/metrics/prometheus`

but something is odd. everytime the metrics are crawled, there are a lot of Warnings in Autonity and Prometheus will fail with `invalid metric type "snap_1_0x00 gauge"`

```
WARN [12-10|10:13:23.480] Unknown Prometheus metric type           type=*metrics.StandardBufferedGauge
WARN [12-10|10:13:23.480] Unknown Prometheus metric type           type=*metrics.StandardBufferedGauge
WARN [12-10|10:13:23.480] Unknown Prometheus metric type           type=*metrics.StandardBufferedGauge
WARN [12-10|10:13:23.480] Unknown Prometheus metric type           type=*metrics.StandardBufferedGauge
```

https://github.com/autonity/autonity/blob/4504e8acccca8ab65f8aba63a2674f51bc6250e6/metrics/prometheus/prometheus.go#L61

**Comment by ThomasBlock** [comment]
As the metric definition is 
`# TYPE p2p_tracked_aut-snap_1_0x00`
it seems like a hyphen is not allowed in the metric name

**Comment by yazzaoui** [comment]
Thank you for raising this issue, we will look into it. In the meantime, InfluxDB which we've been using internally works without problems.

**Comment by yannickhilber** [comment]
I understand InfluxDB is working but as a validator all the chains we're running support Prometheus. It's too much effort to set up InfluxDB for a single chain. At the same time, it's not acceptable for us to be blind and don't know if we're properly supporting a project. 

Can you consider making this small change very soon?

**Comment by vpiyush** [comment]
Yes, This fix will be available soon.
