### ISSUE TITLE
Invalid metric format is breaking Prometheus polling: p2p_egress_aut-snap_1_0x01

### ISSUE THREAD

**Issue by kernelpanic9** [autonity/autonity#899]
### Description

Prometheus is issuing an error when trying to poll autonity metrics 

Offending metric: `p2p_egress_aut-snap_1_0x01`

Prometheus error: `invalid metric type "snap_1_0x01 gauge"`

Metrics shouldn't have `-` symbol.
...

### System Information

Autonity Version: `0.12.2`

**Comment by vpiyush** [comment]
Fixed #932
