### ISSUE TITLE
Implement state/logic separation for LNTN

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#900]
In order to facilitate upgrades for the LNTN contract, a separation of state and logic is essential. The process involves two main steps:

1. Deployment of the LNTN 'Logic' Contract at Genesis: Initially, the 'logic' contract of the LNTN is deployed. This deployment occurs when calling the autonity contract constructor. The 'logic' contract contains the core functionality and rules of the LNTN system but does not hold any state or user-specific data. By isolating the logic in this manner, we ensure that the fundamental operations of the contract can be upgraded without affecting the state.

2. Deployment of the 'State' Contract at Validator Registration: The 'state' contract is deployed separately when a validator registers on the network. The state contract is responsible for storing all the state information, such as user balances, claimable rewards, etc. It's designed to interact with the logic contract.

**Use of DelegateCall for Interaction**: DelegateCall is a feature in the evm that allows one contract (in this case, the state contract) to call the functions of another contract (the logic contract) while maintaining its own state. This is done via the fallback function, a default function in Ethereum smart contracts that is executed when a contract receives Ether or when a function that doesn't exist in the contract is called.

**Comment by lorenzo-dev1** [comment]
Closing as done
