### ISSUE TITLE
Allow GOGC config to be set more than 100

### ISSUE THREAD

**Issue by vpiyush** [autonity/autonity#905]
### Description

In our performance test, we played with different GOGC setting and have come up with a better value for GOGC, which optimizes CPU utilization at the cost of higher resident memory.  What does GOGC do?

> The GOGC environment variable allows you to set the garbage collection target percentage. This percentage controls the aggressiveness of the garbage collector. The default value is 100, which means the garbage collector will run when the heap size (the amount of memory allocated) doubles since the last collection.

Currently Autonity client doesn't support setting the GOGC value more than 100. We should support setting upto 500. 

### Impact of GOGC
Below table depicts the impact of various GOGC values on CPU and memory. These readings were taken for a test setup of 40 nodes running 400 TPS.

| GOGC  | Avg Memory | Max Memory | Avg CPU Usage |
|-------|------------|------------|---------------|
| 1000  | 4.38 GB    | 8.64 GB    | 22.25%        |
| 500   | 2.39 GB    | 4.26 GB    | 23%         |
| 100   | 757 MB     | 1.03 GB    | 26.75%         |

From these results, It is evident that having GOGC at 500 gives us the most optimal CPU and memory utilization.

**Comment by lorenzo-dev1** [comment]
Any idea of why originally it was limited to max 100?

**Comment by vpiyush** [comment]
There is no description of the choice of GOGC value. But May be they chose it because it's a default setting and you can't really take advantage of it without sacrificing memory.

Setting 500 means the next GC cycle would wait for the live heap to become 5 times the memory that was collected in the last cycle. Though many other minute details also influence this Here is the quote from the Go documentation

> The heap target controls GC frequency: the bigger the target, the longer the GC can wait to start another mark phase and vice versa. While the precise formula is useful for making estimates, it's best to think of GOGC in terms of its fundamental purpose: a parameter that picks a point in the GC CPU and memory trade-off. The key takeaway is that doubling GOGC will double heap memory overheads and roughly halve GC CPU cost, and vice versa. (To see a full explanation as to why, see the [appendix](https://tip.golang.org/doc/gc-guide#Additional_notes_on_GOGC).)

**Comment by Jason-Zhangxin-Chen** [comment]
Just wondering if we need to update the recommened HW spec to run Autonity validator node after we tune this to 500. @cmjc

**Comment by cmjc** [comment]
Yes. the HW Requirements for AGC are currently stated as:


Requirement | At least | Recommended
-- | -- | --
OS | Ubuntu 20.04 LTS | Ubuntu 20.04 LTS
CPU | 3.10 GHz with 8 CPU’s | 3.10 GHz with 16 CPU’s
RAM | 8GB | 16GB
Storage | 1024GB free storage for full nodes and Validators | 1024 GB free storage for full nodes and validators
Network interface | 200 Mbit/s | 200 Mbit/s

What is the impact on RAM RQ?  (How much of RAM is allocated to stack memory, how much to heap memory?)

**Comment by lorenzo-dev1** [comment]
I am wondering if the performance benefit is worth the risk of having higher memory consumption. More specifically is the GC aware of the % amount of free RAM? Does it run more frequently if there is less free memory available?

**Comment by vpiyush** [comment]
Are you referring to the OOM panics? With our current recommended 8/16 GB RAM we have enough buffer but We can make GC be aware of free RAM and make decision based on it.

Also, This is still an option which can be changed while starting the client.

**Comment by lorenzo-dev1** [comment]
> Are you referring to the OOM panics?

yes

> We can make GC be aware of free RAM and make decision based on it.

Oh ok how can we do that?

> Also, This is still an option which can be changed while starting the client.
> Ah - --cache.gc under PERFORMANCE TUNING OPTIONS - https://docs.autonity.org/reference/cli/agc/

I am not sure that directly changes the `gogc` percentage. If I understood correctly the computations, if leaving everything default:
- with original version `gogc = max(20, min(100, 100 / (4096/1024)) = 25`
- with modified version `gogc = max(20, min(500, 500 / (4096/1024)) = 125`

The generic formula being `gogc = max(20,min(100, 100/ (cache/1024))`.

So I guess we can modify the gogc parameter indirectly by specifying the `--cache` parameter. But is there a way to change directly the gogc value?

**Comment by vpiyush** [comment]
> Oh ok interesting how can we do that?

runtime.setMemoryLimit 

> The generic formula being gogc = max(20,min(100, 100/ (cache/1024)). I guess so that if the node is configured to use a big database cache, the gogc will not uselessly run very often.

Lower the GC value the more frequently it runs. So for bigger cache value it runs more frequently. 

> So I guess we can modify the gogc parameter indirectly by specifying the --cache parameter. But is there a way to change directly the gogc value?

There is no specific flag only affecting the GOGC value. As far as I understood the reason is this - Database cache and other caches(trie-cache, snapshot cache) are the percentage value of the cache, and cache does directly set the GOGC value but capping it to the max 100/500. GOGC value is inversely proportional to the cache values to control the trigger frequency.  High-Cache -> Frequent GC, Low-Cache -> Delayed GC.

**Comment by lorenzo-dev1** [comment]
Oh ok I see. 

I don't have a super strong opinion on this, but tbh I would rather have a flag that allows setting the GC additionally to the normal cache computation... I don't really get why GC should be related to the cache size, other than that if you have a big cache you want GC to run more often to reduce the overall memory usage? 

But what if the validator has a lot of memory available, maybe he still wants high cache and delayed GC?

**Comment by vpiyush** [comment]
>  I don't really get why GC should be related to the cache size, other than that if you have a big cache you want GC to run more often to reduce the overall memory usage?

I think it's reasonable to have it related, i would try to describe here as why that makes sense, GOGC value determines the next GC trigger for e.g. let's say for the live heap size of 1GB if we set the GOGC to 300 the next GC would be triggered when heap allocation reaches 4GB. Now the bigger the caches the bigger the live heap size. So for the sake of argument say for big cache size the live heap becomes 4GB with the GOGC value 300 the trigger would be at 16GB. that would risk an OOM trigger. so For higher cache size it's reasonable to have the GOGC at 25 or 50 max. which is more than enough memory buffer.

> But what if the validator has a lot of memory available, maybe he still wants high cache and delayed GC to save on CPU?

I don't believe we can expect most people to know how a higher cache coupled with high GOGC could trigger an OOM panic. But we can tune it further for such requirement so that they can take advantage of it. This is up for discussion from my point of view.

> But I would approve the change if we can run 100 committee member with max TPS supported and still have a decent memory consumption (<16 GB?). Do you think that will happen with 500 as max @vpiyush ?

I have run with 75 nodes (TPS sent as 1000, tx pool getting filled) with max memory consumption being approximately ~9GB. So I would say it should be fine. though we should still test 100 nodes, Perhaps we could reduce it to 300 being on the safer side.

**Comment by lorenzo-dev1** [comment]
> I think it's reasonable to have it related ...

Got it makes sense

> I don't believe we can expect most people to know how a higher cache coupled with high GOGC could trigger an OOM panic. But we can tune it further for such requirement so that they can take advantage of it. This is up for discussion from my point of view.

I think we shouldn't constraint the validators by picking cpu-memory tradeoff for them, but instead let them be free of making their choice based on the hardware they have. Or at least allow them to do so if they have the know-how required. But I think this is out of scope of this issue.

> I have run with 75 nodes (TPS sent as 1000, tx pool getting filled) with max memory consumption being approximately ~9GB. So I would say it should be fine. though we should still test 100 nodes, Perhaps we could reduce it to 300 being on the safer side.

Yeah I think it is fine if we agree on raising the minimum memory required from 8GB to 16GB here https://docs.autonity.org/node-operators/install-aut/#hardware.

**Comment by vpiyush** [comment]
done with #945
