### ISSUE TITLE
Implement BufferedGauge support for Prometheus .

### ISSUE THREAD

**Issue by vpiyush** [autonity/autonity#913]
There is a custom-type BufferedGauge to report and visualize instant metrics. This is only supported for influxDB-based reporting for now. and there is no corresponding type in Prometheus to handle this yet. which generates a warning(temporarily suppressed by ignoring the type) whenever there is a pull from Prometheus also these metrics can not be visualized when using Prometheus.

There is a need to translate the buffered Gauge in a way such that a Prometheus scrapper can interpret the data correctly.

**Comment by yazzaoui** [comment]
I'm perfectly happy to keep the current logic and reserve collection for advanced metric to influxdb only
