### ISSUE TITLE
Loss of funds when using CAX

### ISSUE THREAD

**Issue by SergeyMitk** [autonity/autonity#915]
1. I bought 2000 ATN on the CAX exchange.
2. I made a withdrawal transaction from the exchange account to the validator address (address: 0x18E1a1a0B942519e12cC524d9Acc573C7c56b12a).
3. At the time of the transaction the API was not availaible, transaction status:dropped/replaced
   explorer link is: https://piccadilly.autonity.org/tx/0x1171589c21642f0c16b5bdac1e09d72bb97586744f928e699f79b35290c87d18
4. Funds were debited from the exchange account, but did not arrive at the validator address and did not come back to the exchange account after the API worked (they were lost).
5. Feel free to DM me in Discord: sergey.mitk if you need more info.

**Comment by cmjc** [comment]
Hi @SergeyMitk - this has been analysed  and outcome is so:

- 0x18E1a1a0B942519e12cC524d9Acc573C7c56b12a withdraw at 2023-12-22 07:42:07.556633 with txid 209089 was marked as failed. Further, subsequent withdraws from the account with txid's 209091, 209092, and 209093 also failed.
- These failed requests were related to the RPC1 node going down.
- Withdraws can be marked as failed if the CAX cannot successfully obtain the tx receipt 120 seconds after submitting the tx to the RPC node. In this scenario, the CAX cannot determine if the tx will be mined or not, hence marking as failed.
- Reviewing the transactions, your PCGC account on Piccadilly Testnet 0x18E1a1a0B942519e12cC524d9Acc573C7c56b12a is due a credit of: ATN: 2505, NTN: 3.

This has been transferred to your PCGC account on Piccadilly Testnet.

This is a Piccadilly Circus Game Competition and not an autonity client related issue, so closing this. If you have additional questions on this, please raise them in the Autonity Discord channel games-help - https://discord.com/channels/753937111781998605/1067049380126937219

Thanks.

**Comment by aiman** [comment]
In case of any issues with the Piccadilly Circus Games Competition, please reach out on the Discord channel games-help for support: <https://discord.com/channels/753937111781998605/1067049380126937219>

As this issue relates to the Piccadilly Circus Game Competition, and is not an issue with the Autonity Go Client, we will reach out to you on Discord to resolve it.
