### ISSUE TITLE
getValidatorAccusation contract call reverts with panic

### ISSUE THREAD

**Issue by szemate** [autonity/autonity#951]
### Description

Calling `getValidatorAccusation` with autcli as:
```
aut contract call --address 0x5a443704dd4B594B382c22a083e2BD3090A6feF3 getValidatorAccusation 0x31870f96212787D181B3B2771F58AF2BeD0019Aa
```
results in:
```
web3.exceptions.ContractPanicError: Panic error 0x11: Arithmetic operation results in underflow or overflow.
```
This is the error that web3.py raises when a contract call reverts with panic.

Interestingly, this error only occurs on the Piccadilly testnet. A similar call on the Bakerloo testnet results in:
```
web3.exceptions.ContractLogicError: execution reverted: no accusation
```
as expected.

### System Information

- Piccadilly network through the RPC endpoint https://rpc1.piccadilly.autonity.org, accessed on 29-02-2024.
- aut 0.3.0 with the patch https://github.com/autonity/autonity.py/pull/46 (otherwise the error is not human readable)

**Comment by yazzaoui** [comment]
Piccadilly testnet is running on Autonity v0.12.3 which wasn't reverting with the correct reason when calling this function. The appropriate revert reason was later on added with the recent release running on Bakerloo.
Closing.
