### ISSUE TITLE
Readme.md - git clone commands

### ISSUE THREAD

**Issue by nightfallinme** [autonity/autonity#953]
```
Git clone git@*.* 
```

commands giving a permission denied (publickey) error, either;

- set git repository for easier access 
or
- change the guide commands as      
                    ```
                    git clone https://github.com/autonity/autonity.git
                     ```

will prevent a lot of potential questions on the upcoming game round 5.

**Comment by nightfallinme** [comment]
solved already.

**Comment by nightfallinme** [comment]
README / base screen of github still shows old commands.

**Comment by lorenzo-dev1** [comment]
This is not an Autonity issue. Whether one can clone the repo using ssh or https entirely depends on his profile configuration.

Namely if you do not have setup an ssh key in your github profile, then cloning using ssh will fail.
