### ISSUE TITLE
Accountability Contract:  canSlash contract call reverts correctly but doesn't return a revert reason

### ISSUE THREAD

**Issue by cmjc** [autonity/autonity#954]
### Description

Calling `canSlash` with autcli to see if a validator is slashable:
```
aut contract call --address 0x5a443704dd4B594B382c22a083e2BD3090A6feF3 canSlash 0x4B241e33CEFbeF5fFE87CF81C56f19D6321536c4 10 1245
```
returns reverted, but without a revert reason:
```
web3.exceptions.ContractLogicError: execution reverted
```
If calling `getValidatorAccusation` and there are no accusations, a revert reason of `no accusation` is returned:

```
aut contract call --address 0x5a443704dd4B594B382c22a083e2BD3090A6feF3 getValidatorAccusation 0x6558D2cEEb4a9Fe9c9cF19A3F6EBE7D45C30efaF
web3.exceptions.ContractLogicError: execution reverted: no accusation
```

### System Information

- Piccadilly network through the RPC endpoint https://rpc1.piccadilly.autonity.org, accessed on 05-03-2024.
- aut 0.4.0 

### Rationale

Returning a revert reason would be more informative to the user.

**Comment by Jason-Zhangxin-Chen** [comment]
Hi @cmjc, from your context, rule NO. 10 is not defined in the rule set: 
```solidity
    // Must match autonity/types.go
    enum Rule {
        PN,
        PO,
        PVN,
        PVO,
        PVO12,
        C,
        C1,

        InvalidProposal, // The value proposed by proposer cannot pass the blockchain's validation.
        InvalidProposer, // A proposal sent from none proposer nodes of the committee.
        Equivocation    // Multiple distinguish votes(proposal, prevote, precommit) sent by validator.
    }

    // @dev return true if sending the event can lead to slashing
    function canSlash(address _offender, Rule _rule, uint256 _block) public view returns (bool) {
        uint256 _severity = _ruleSeverity(_rule);
        uint256 _epoch = autonity.getEpochFromBlock(_block);

        return slashingHistory[_offender][_epoch] < _severity ;
    }
```
As the typing system limits the input of _rule should be a type of Rule, from inside the canSlash funtion we cannot capture such error. Thus from AUT tool side, we can do some check on it. This issue so move to Aut tool.

**Comment by cmjc** [comment]
Thanks @Jason-Zhangxin-Chen , closing issue and raising in `aut` repo - https://github.com/autonity/aut/issues/151

**Comment by aiman** [comment]
Hi @Jason-Zhangxin-Chen @cmjc can you please explain why this function is reverting here?

**Comment by Jason-Zhangxin-Chen** [comment]
> Hi @Jason-Zhangxin-Chen @cmjc can you please explain why this function is reverting here?

Hi @aiman, the typing of Rule includes 0~9 rules in enum, while in Jay's test context, we have an out of range rule ID be taken as the input, thus it might be reverted by type cast failures, thus it is worth to retest it with right range ID. However, this canSlash() function is a protocol function reserved for accountability protocols, it is not used by end clients, it shouldn't be used by aut cli.

**Comment by cmjc** [comment]
Hi @Jason-Zhangxin-Chen @aiman , I put a rule ID of 10, which was incorrect - index starts at 0, the highest rule ID is 9, not 10. I should have used `9` not `1§0` in my call.  So @Jason-Zhangxin-Chen is correct - it reverted because I put in an invalid data value.

When I call it with correct values for rule ID (i.e. 0 - 9), it returns correctly:

```
aut contract call --address 0x5a443704dd4B594B382c22a083e2BD3090A6feF3 canSlash 0x8fc7Bc997be00Ccd4024064b98FeAbe519C22b67 9 12345
true
```

That is a correct response looking at the validator data on-chain.

This function is intended for internal use only, even although it is public. This raises **2 questions on functions intended for internal protocol use only**. Should they be:

1. be documented in the docs?
2. be callable publicly?


On **1**, no. An issue to remove them following team discussion today has been logged in docs.autonity.org - https://github.com/autonity/docs.autonity.org/issues/177. Rationale: functions intended for internal use only don't need to be documented in the user docs.

On **2**, this is to be decided. Applying access control modifiers to them was discussed today at standup by @yazzaoui

**Comment by aiman** [comment]
> from inside the canSlash funtion we cannot capture such error

This is not correct @Jason-Zhangxin-Chen as it is possible to check for invalid `_rule` value, for example: `type(Rule).min <= _rule <= type(Rule).max`.

**Comment by lorenzo-dev1** [comment]
Closing since the check is now implemented.
