### ISSUE TITLE
Run Autonity as Docker image with the option "--syncmode" = "light" doesn't work

### ISSUE THREAD

**Issue by jfaiza** [autonity/autonity#960]
hello,

I try to test to run Autonity as Docker image with the option "--syncmode" = "light" but it donesn't work !

Example to generate the problem:
docker run -it -d --volume $(pwd)/autonity-chaindata:/autonity-chaindata --publish 8545:8545 --publish 8546:8546 --publish 30303:30303 --publish 30303:30303/udp  --publish 20203:20203 --publish 6060:6060 --name autonity --rm ghcr.io/autonity/autonity:latest --datadir ./autonity-chaindata  --piccadilly --http  --http.addr 0.0.0.0 --http.api aut,eth,net,txpool,web3,admin  --http.vhosts \* --ws  --ws.addr 0.0.0.0 --ws.api aut,eth,net,txpool,web3,admin  --nat extip: ip_address --syncmode light

**Comment by cmjc** [comment]
Hi @jfaiza - Light sync mode and the LES Protocol isn't supported by this version of the protocol.

This should be noted in the docs.  A PR for this has is here:  https://github.com/autonity/docs.autonity.org/pull/165

**Comment by yazzaoui** [comment]
Closing as light sync mode is currently non-supported.
