### ISSUE TITLE
A bug in the implementation of tendermint line36 upon-condition, we need to fix it and add extra tests to cover it.

### ISSUE THREAD

**Issue by Jason-Zhangxin-Chen** [autonity/autonity#978]
There is an interesting mismatch between our tendermint implementation and the tendermint protocol. As line 36 of page 6 of https://arxiv.org/pdf/1807.04938 specified: for the 1st time on that upon-condition, we'd need to do the locking of value, round, and setting of valid value and valid round. However in our implementation, we introduced a flag: https://github.com/autonity/autonity/blob/develop/consensus/tendermint/core/core.go#L352 with which to be reset on each round start, I think this resetting is not need at all, otherwise we might overwrite the locked value, locked round, valid value and valid round. 
We need to fix it and add extra tests to cover this scenario.

**Comment by vpiyush** [comment]
I think this makes sense, we should probably set the flag only when round=0

**Comment by lorenzo-dev1** [comment]
I think that the current implementation is correct. It is allowed for a node to change `lockedValue` and `lockedRound` if it receives a quorum of prevotes for another value in a later round. This behaviour is called [flip-flopping](https://github.com/tendermint/tendermint/blob/v0.34.x/spec/light-client/accountability/README.md#flip-flopping).

Moreover the definition of `for the first time` from the tendermint paper is:

> with ”for the first time” constraint to denote that it is triggered only the first time a corresponding condition evaluates to true.

They do not clearly specify if they mean "first time in a round" or "first time in an height". However from condition on lines 34 and 47 we can infer that they mean "first time in a round", since timeouts can be scheduled once every round.

**Comment by Jason-Zhangxin-Chen** [comment]
> I think that the current implementation is correct. It is allowed for a node to change `lockedValue` and `lockedRound` if it receives a quorum of prevotes for another value in a later round. This behaviour is called [flip-flopping](https://github.com/tendermint/tendermint/blob/v0.34.x/spec/light-client/accountability/README.md#flip-flopping).
> 
> Moreover the definition of `for the first time` from the tendermint paper is:
> 
> > with ”for the first time” constraint to denote that it is triggered only the first time a corresponding condition evaluates to true.
> 
> They do not clearly specify if they mean "first time in a round" or "first time in an height". However from condition on lines 34 and 47 we can infer that they mean "first time in a round", since timeouts can be scheduled once every round.
> 
> Additionally that is also why we have no rules in the FD to detect this kind of behaviour (commit for V, then later on commit for V').
> 
> This also seems to match with CometBFT implementation: https://github.com/cometbft/cometbft/blob/df28e73d35eb82c439167541f308930a8628edf3/internal/consensus/state.go#L1660

Thank you so much, Lorenzo. Now I realized the 'for the first time' in the context is of within a round, By according to the statement of `However, it is possible to change the locked value if in a future round r' > r, if the process receives proposal and 2f + 1 prevotes for a different value v'. In this case, p could send a prevote/precommit for id(v').` I think we are good at current develop, I will close this issue now. Thanks!

**Comment by Jason-Zhangxin-Chen** [comment]
This was a mis-understanding of the statement in the protocol, please refer to the discussion context. Close it now.
